[pytest]
pythonpath = projects
markers =
    api: API tests (bank_api)
    ui: UI tests (saucedemo)
    account: /account tests
    admin: /admin tests
    credit: /credit tests
    auth: /auth tests
